## 框架的核心配置项和菜单结构。 业务项目需在 application-data.yml 中进行配置。
data:
  # 数据库配置元数据
  configs:
    - group-name: 邮件配置
      children:
        - code: email.from
          name: 邮件发送账号
        - code: email.pass
          name: 邮件发送密码
    - group-name: 网站配置
      children:
        - code: sys.copyright
          name: 版权信息
        - code: sys.loginBackground
          name: 登录背景图
        - code: sys.loginBoxBottomTip
          name: 登录框下面的提示
        - code: sys.title
          name: 站点标题
        - code: sys.waterMark
          name: 开启水印
          value-type: boolean
          description: 在所有页面增加水印
    - group-name: 系统配置
      children:
        - code: sys.baseUrl
          name: 请求基础地址
          description: 非必填，可用于拼接完整请求地址
        - code: sys.jwtSecret
          name: jwt密码
  # 菜单配置
  menus:
    - name: 我的任务
      id: myFlowableTask
      path: /flowable/task
      seq: -1
      refresh-on-tab-click: true
      message-count-url: /admin/flowable/my/todoCount
      perms:
        - perm: myFlowableTask:manage
          name: 任务管理
    - id: sys
      name: 系统管理
      seq: 10000 # 系统管理排在后面
      children:
        - id: sysOrg
          name: 机构管理
          path: /system/org
          icon: ApartmentOutlined
          perms:
            - name: 保存
              perm: sysOrg:save
            - name: 查看
              perm: sysOrg:view
            - name: 删除
              perm: sysOrg:delete

        - id: sysUser
          name: 用户管理
          path: /system/user
          icon: UserOutlined
          perms:
            - name: 列表
              perm: sysUser:view
            - name: 保存
              perm: sysUser:save
            - name: 删除
              perm: sysUser:delete
            - name: 重置密码
              perm: sysUser:resetPwd
            - name: 授权数据
              perm: sysUser:grantPerm

        - id: sysRole
          name: 角色管理
          path: /system/role
          icon: IdcardOutlined
          perms:
            - name: 保存
              perm: sysRole:save
        - id: sysManual
          name: 操作手册
          path: /system/sysManual
          icon: CopyOutlined
          perms:
            - perm: sysManual:view
              name: 查看
            - perm: sysManual:delete
              name: 删除
            - perm: sysManual:save
              name: 保存

        - id: sysConfig
          name: 系统设置
          path: /system/config
          icon: SettingOutlined
          perms:
            - perm: sysConfig:view
              name: 查看
            - perm: sysConfig:save
              name: 保存
        - id: sysDict
          name: 数据字典
          path: /system/dict
          icon: FileSearchOutlined
          perms:
            - name: 查看
              perm: sysDict:view
            - name: 保存
              perm: sysDict:save
            - name: 删除
              perm: sysDict:delete
        - id: sysFile
          name: 存储文件
          path: /system/file
          icon: FolderOpenOutlined
          perms:
            - perm: sysFile:view
              name: 查看
            - perm: sysFile:delete
              name: 删除

        - id: job
          name: 作业调度
          path: /system/job
          icon: OrderedListOutlined
          perms:
            - perm: job:view
              name: 查看
            - perm: job:save
              name: 保存
            - name: 执行一次
              perm: job:triggerJob
            - name: 清理日志
              perm: job:jobLogClean
        - id: sysLog
          name: 操作日志
          path: /system/log
          icon: FileSearchOutlined
          perms:
            - name: 查看
              perm: sysLog:view
        - id: api
          name: 接口管理
          icon: ApiOutlined
          path: /system/api
          perms:
            - name: 管理
              perm: api
        - id: flowableModel
          name: 流程引擎
          path: /flowable
          perms:
            - perm: flowableModel:design
              name: 设计
            - perm: flowableModel:deploy
              name: 部署
            - perm: flowableTask:setAssignee
              name: 动态修改受理人
            - perm: flowableInstance:close
              name: 终止流程
        - id: ureport
          name: 报表管理
          icon: TableOutlined
          seq: 101
          path: /ureport
          perms:
            - perm: ureport:view
              name: 查看
            - perm: ureport:design
              name: 设计
