## 框架的核心配置项和菜单结构。 业务项目需在 application-data.yml 中进行配置。
data:
  # 数据库配置元数据
  configs:
    - group-name: 邮件配置
      children:
        - code: email.from
          name: 邮件发送账号
        - code: email.pass
          name: 邮件发送密码
    - group-name: 网站配置
      children:
        - code: sys.copyright
          name: 版权信息
        - code: sys.loginBackground
          name: 登录背景图
        - code: sys.loginBoxBottomTip
          name: 登录框下面的提示
        - code: sys.title
          name: 站点标题
        - code: sys.waterMark
          name: 开启水印
          value-type: boolean
          description: 在所有页面增加水印
    - group-name: 系统配置
      children:
        - code: sys.baseUrl
          name: 请求基础地址
          description: 非必填，可用于拼接完整请求地址
        - code: sys.jwtSecret
          name: jwt密码
  # 菜单配置
  menus:
    - name: 我的任务
      id: myFlowableTask
      path: /flowable/task
      seq: -1
      refresh-on-tab-click: true
      message-count-url: /admin/flowable/my/todoCount
      perm-names: [ 任务管理 ]
      perm-codes: [ myFlowableTask:manage ]
    - id: sys
      name: 系统管理
      seq: 10000 # 系统管理排在后面
      children:
        - id: sysOrg
          name: 机构管理
          path: /system/org
          icon: ApartmentOutlined
          perm-names: [ 保存 ,查看,删除 ]
          perm-codes: [ sysOrg:save,sysOrg:view,sysOrg:delete ]
        - id: sysUser
          name: 用户管理
          path: /system/user
          icon: UserOutlined
          perm-names: [ 列表,保存,删除,重置密码,授权数据 ]
          perm-codes: [ sysUser:view,sysUser:save,sysUser:delete,sysUser:resetPwd,sysUser:grantPerm ]
        - id: sysRole
          name: 角色管理
          path: /system/role
          icon: IdcardOutlined
          perm-names: [ 保存 ]
          perm-codes: [ sysRole:save ]
        - id: sysManual
          name: 操作手册
          path: /system/sysManual
          icon: CopyOutlined
          perm-names: [ 查看,删除,保存 ]
          perm-codes: [ sysManual:view,sysManual:delete,sysManual:save ]
        - id: sysConfig
          name: 系统设置
          path: /system/config
          icon: SettingOutlined
          perm-names: [ 查看,保存 ]
          perm-codes: [ sysConfig:view,sysConfig:save ]
        - id: sysDict
          name: 数据字典
          path: /system/dict
          icon: FileSearchOutlined
          perm-names: [ 查看,保存,删除 ]
          perm-codes: [ sysDict:view,sysDict:save,sysDict:delete ]
        - id: sysFile
          name: 存储文件
          path: /system/file
          icon: FolderOpenOutlined
          perm-names: [ 查看,删除 ]
          perm-codes: [ sysFile:view,sysFile:delete ]
        - id: job
          name: 作业调度
          path: /system/job
          icon: OrderedListOutlined
          perm-names: [ 查看,保存,执行一次,清理日志 ]
          perm-codes: [ job:view,job:save, job:triggerJob,job:jobLogClean ]
        - id: sysLog
          name: 操作日志
          path: /system/log
          icon: FileSearchOutlined
          perm-names: [ 查看 ]
          perm-codes: [ sysLog:view ]
        - id: api
          name: 接口管理
          icon: ApiOutlined
          path: /system/api
          perm-names: [ 管理 ]
          perm-codes: [ api ]
        - id: flowableModel
          name: 流程引擎
          path: /flowable
          perm-names: [ 设计,部署,动态修改受理人,终止流程 ]
          perm-codes: [ flowableModel:design,flowableModel:deploy,flowableTask:setAssignee,flowableInstance:close ]
        - id: ureport
          name: 报表管理
          icon: TableOutlined
          seq: 101
          path: /ureport
          perm-names: [ 查看,设计 ]
          perm-codes: [ ureport:view,ureport:design ]
