data:
  configs:
    - group-name: 邮件配置
      children:
        - code: email.from
          name: 邮件发送账号
        - code: email.pass
          name: 邮件发送密码
    - group-name: 网站配置
      children:
        - code: sys.copyright
          name: 版权信息
        - code: sys.loginBackground
          name: 登录背景图
        - code: sys.loginBoxBottomTip
          name: 登录框下面的提示
        - code: sys.logo
          name: 站点logo
          value-type: img
        - code: sys.title
          name: 站点标题
        - code: sys.waterMark
          name: 开启水印
          value-type: boolean
          description: 在所有页面增加水印

    - group-name: 系统配置
      children:
        - code: sys.baseUrl
          name: 请求基础地址
          description: 非必填，可用于拼接完整请求地址
        - code: sys.default.password
          name: 默认密码
        - code: sys.jwtSecret
          name: jwt密码
        - code: sys.printAssertException
          name: 是否打印Assert方法抛出的异常
          value-type: boolean


