data:
  menus:
    - id: sys
      name: 系统管理
      seq: 10000 # 系统管理排在后面
      children:
        - id: sysOrg
          name: 机构管理
          path: /system/org
          icon: ApartmentOutlined
          perms:
            - name: 保存
              perm: sysOrg:save
            - name: 查看
              perm: sysOrg:view
            - name: 删除
              perm: sysOrg:delete

        - id: sysUser
          name: 用户管理
          path: /system/user
          icon: UserOutlined
          perms:
            - name: 列表
              perm: sysUser:view
            - name: 保存
              perm: sysUser:save
            - name: 删除
              perm: sysUser:delete
            - name: 重置密码
              perm: sysUser:resetPwd
            - name: 授权数据
              perm: sysUser:grantPerm

        - id: sysRole
          name: 角色管理
          path: /system/role
          icon: IdcardOutlined
          perms:
            - name: 保存
              perm: sysRole:save
        - id: sysManual
          name: 操作手册
          path: /system/sysManual
          icon: CopyOutlined
          perms:
            - perm: sysManual:view
              name: 查看
            - perm: sysManual:delete
              name: 删除
            - perm: sysManual:save
              name: 保存

        - id: sysConfig
          name: 系统配置
          path: /system/config
          icon: SettingOutlined
          perms:
            - perm: sysConfig:view
              name: 查看
            - perm: sysConfig:save
              name: 保存
        - id: sysDict
          name: 数据字典
          path: /system/dict
          icon: FileSearchOutlined
          perms:
            - name: 查看
              perm: sysDict:view
            - name: 保存
              perm: sysDict:save
            - name: 删除
              perm: sysDict:delete
        - id: sysFile
          name: 文件管理
          path: /system/file
          icon: FolderOpenOutlined
          perms:
            - perm: sysFile:view
              name: 查看
            - perm: sysFile:delete
              name: 删除


        - id: sysLog
          name: 操作日志
          path: /system/log
          icon: FileSearchOutlined
          perms:
            - name: 查看
              perm: sysLog:view
        - id: api
          name: 接口管理
          icon: ApiOutlined
          path: /system/api
          perms:
            - name: 管理
              perm: api

        - id: job
          name: 作业调度
          path: /system/job
          icon: OrderedListOutlined
          perms:
            - perm: job:view
              name: 查看
            - perm: job:save
              name: 保存
            - name: 执行一次
              perm: job:triggerJob
            - name: 清理日志
              perm: job:jobLogClean
