data:
  menus:
    - id: sys
      children:
        - id: flowableModel
          name: 流程引擎
          path: /flowable
          perms:
            - perm: flowableModel:design
              name: 设计
            - perm: flowableModel:deploy
              name: 部署
            - perm: flowableTask:setAssignee
              name: 动态修改受理人





    - name: 我的任务
      id: myFlowableTask
      path: /flowable/task
      seq: -1
      refresh-on-tab-click: true
      message-count-url: /admin/flowable/my/todoCount
      perms:
        - perm: myFlowableTask:manage
          name: 任务管理

