data:
  menus:
    - id: sys
      name: 系统管理
      children:
        - id: sysOrg
          name: 机构管理
          path: /system/org
          icon: ApartmentOutlined
          perms:
            - name: 保存
              perm: sysOrg:save
            - name: 查看
              perm: sysOrg:page
            - name: 排序
              perm: sysOrg:sort
            - name: 禁用
              perm: sysOrg:disableAll
            - name: 启用
              perm: sysOrg:enableAll
            - name: 查看
              perm: sysOrg:detail
            - name: 删除
              perm: sysOrg:delete

        - id: sysUser
          name: 用户管理
          path: /system/user
          icon: UserOutlined
          perms:
            - name: 列表
              perm: sysUser:page
            - name: 保存
              perm: sysUser:save
            - name: 删除
              perm: sysUser:delete
            - name: 重置密码
              perm: sysUser:resetPwd
            - name: 授权数据
              perm: sysUser:grantPerm

        - id: sysRole
          name: 角色管理
          path: /system/role
          icon: IdcardOutlined
          perms:
            - name: 保存
              perm: sysRole:save
        - id: sysManual
          name: 操作手册
          path: /system/sysManual
          icon: CopyOutlined
          perms:
            - perm: sysManual:page
              name: 查看
            - perm: sysManual:delete
              name: 删除
            - perm: sysManual:save
              name: 保存

        - id: sysConfig
          name: 系统参数
          path: /system/config
          icon: SettingOutlined
          perms:
            - perm: sysConfig:page
            - perm: sysConfig:save
            - perm: sysConfig:delete
        - id: sysDict
          name: 数据字典
          path: /system/dict
          icon: FileSearchOutlined
          perms:
            - name: 查看
              perm: sysDict:view
            - name: 保存
              perm: sysDict:save
            - name: 删除
              perm: sysDict:delete
        - id: sysFile
          name: 存储文件
          path: /system/file
          icon: FolderOpenOutlined
          perms:
            - perm: sysFile:page
            - perm: sysFile:delete

        - id: jobMgr
          name: 作业调度
          icon: ScheduleOutlined
          children:
            - id: job
              name: 作业管理
              path: /job
              icon: OrderedListOutlined
              perms:
                - perm: job:page
                - perm: job:save
                - name: 执行一次
                  perm: job:triggerJob
                - name: 清理日志
                  perm: job:jobLogClean
            - id: jobLog
              name: 作业日志
              path: /job/logList
              icon: FileOutlined

            - id: jobStatus
              name: 作业监控
              path: /job/status
              icon: FundViewOutlined
              perms:
                - name: 任务状态
                  perm: jobStatus:info
                - name: 统计报表
                  perm: jobStatus:statsTotal
        - id: sysLog
          name: 操作日志
          path: /system/log
          icon: FileSearchOutlined
          perms:
            - name: 查看
              perm: sysLog:page


        - id: sys_entity_gen
          name: 生成代码
          path: /dev/code
          icon: JavaScriptOutlined


        - id: api
          name: 开放接口
          icon: ApiOutlined
          children:
            - id: apiAccount
              name: 账户管理
              path: /api
              icon: ApiOutlined
            - id: apiAccountResource
              name: 账户授权
              icon: ApiOutlined
              perms:
                - name: 列表
                  perm: apiAccountResource:page
                - name: 保存
                  perm: apiAccountResource:save
                - name: 删除
                  perm: apiAccountResource:delete
            - id: apiResource
              name: 接口管理
              path: /api/resource
              icon: ApiOutlined
            - id: apiAccessLog
              name: 访问记录
              path: /api/accessLog
              icon: ApiOutlined

    - id: biz
      name: 业务模块
