db_ip: 127.0.0.1
db_port: 3306
db_database: admin-db
db_username: root
db_password: 123456
spring:
  profiles:
    active: default
  application:
    name: admin-framework


logging:
  file:
    path: ./logs
sys:
  reset-admin-pwd: okjt123_
  captcha: false

